services:
  - type: web
    name: pes-face-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
    # Déploiement manuel avec image Docker Hub
    # dockerHub: xavier777501/pes-backend:latest
